---
collections:
  - name: cisco.ios
    version: 2.3.0
  - name: clay584.genie
    version: 0.1.11
  - name: ansible.tower
    version: 3.8.3
  - name: servicenow.itsm
    version: 1.1.0
  - name: ansible.netcommon
    version: 2.2.0
  - name: ansible.utils
    version: 2.3.0
