---
- name: Populate ServiceNow CMDB with Routers
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars_files:
    - ./credentials/servicenow-credentials.yml
    - ./default_vars.yml

  tasks:

  - name: show version
    cisco.ios.ios_command:
      commands:
        - show version
    register: version

  - name: Run command and parse with pyats
    ansible.utils.cli_parse:
      command: "show version"
      parser:
          name: ansible.netcommon.pyats
    register: parser_output

  - name: Show Version - all
    ansible.builtin.debug:
     var: parser_output

  - name: Show Version Details
    ansible.builtin.debug:
     msg:
     - "Hostname: {{ parser_output.parsed.version.hostname }}"
     - "Model: {{ parser_output.parsed.version.chassis }}"
     - "Operating System: {{ parser_output.parsed.version.os }}"
     - "OS Version: {{ parser_output.parsed.version.version }}"
     - "Serial Number: {{ parser_output.parsed.version.chassis_sn }}"
     - "Configuration Register: {{ parser_output.parsed.version.curr_config_register }}"

  - name: Create a configuration item
    servicenow.itsm.configuration_item:
      instance:
        host: "{{ SN_INSTANCE }}.service-now.com"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
      name: "{{ parser_output.parsed.version.hostname }}"
      short_description: "{{ parser_output.parsed.version.chassis }}"
      serial_number: "{{ parser_output.parsed.version.chassis_sn }}"
      sys_class_name: cmdb_ci_ip_router
      environment: production
      category: Hardware
    register: cmdb_router

  # - name: Set Fact Genie Filter
  #   ansible.builtin.set_fact:
  #     pyats_version: "{{ version['stdout'][0] | clay584.genie.parse_genie(command='show version', os='ios') }}"
  #
  # - name: Debug Pyats facts - all
  #   ansible.builtin.debug:
  #    var: pyats_version.version
  #
  # - name: Debug Pyats facts - version
  #   ansible.builtin.debug:
  #    var: pyats_version.version.version
  #
  # - name: Debug Pyats facts - uptime
  #   ansible.builtin.debug:
  #    var: pyats_version.version.uptime
