---
- name: Make Surveys based on backup directories
  hosts: tower
  gather_facts: no
  vars_files:
    - default_vars.yml
    - ./credentials/tower-credentials.yml

  tasks:
    - name: Find /tmp/ios_backups/ all directories, exclude nginx and mysql
      find:
        paths: /tmp/ios_backups/
        recurse: no
        file_type: directory
      register: find_output


    # - debug:
    #     var: find_output

    # - debug:
    #     msg: "{{ item.path }}"
    #   loop: "{{ find_output.files }}"

    - name: Build survey_spec from template
      template:
        src: ./templates/drift_survey.j2
        dest: /tmp/drift_survey.json
      # delegate_to: localhost

    - name: Build survey_spec from template
      template:
        src: ./templates/restore_survey.j2
        dest: /tmp/restore_survey.json

    - name: Build Ansible Tower Config Drift template with Survey
      tower_job_template:
          name: "IOS Check for Configuration Drift"
          job_type: "run"
          inventory: "IOS Github-sourced Routers"
          project: "Ansible IOS Demo Exercises"
          playbook: "ios-drift-detect.yml"
          credential: "maf-ios-demo-private"
          survey_enabled: true
          survey_spec: "{{ lookup('template', '/tmp/drift_survey.json') }}"
          tower_username: "{{ TOWER_USERNAME }}"
          tower_password: "{{ TOWER_PASSWORD }}"
          tower_host: https://ansibletower.michaelanthonyford.com
          validate_certs: no
          diff_mode_enabled: yes
      delegate_to: localhost
      run_once: yes

    - name: Build Ansible Tower Config Restore template with Survey
      tower_job_template:
          name: "IOS Restore Config from Backup"
          job_type: "run"
          inventory: "IOS Github-sourced Routers"
          project: "Ansible IOS Demo Exercises"
          playbook: "ios-restore-config.yml"
          credential: "maf-ios-demo-private"
          survey_enabled: true
          survey_spec: "{{ lookup('template', '/tmp/restore_survey.json') }}"
          tower_username: "{{ TOWER_USERNAME }}"
          tower_password: "{{ TOWER_PASSWORD }}"
          tower_host: https://ansibletower.michaelanthonyford.com
          validate_certs: no
      delegate_to: localhost
      run_once: yes

    - name: Delete drift survey from /tmp directory
      file:
        state: absent
        path: /tmp/drift_survey.json

    - name: Delete restore survey from /tmp directory
      file:
        state: absent
        path: /tmp/restore_survey.json
