---
- name: Clear IOS backups from webserver
  hosts: webserver
  gather_facts: no
  vars_files:
    - default_vars.yml

  tasks:
    - name: Clear existing backups from ios_backups directory
      file:
        state: absent
        path: ~/ios_backups/


- name: Clear IOS backups from Tower Server
  hosts: tower
  gather_facts: no
  vars_files:
    - default_vars.yml
    - ./credentials/tower-credentials.yml

  tasks:
    - name: Clear existing backups from ios_backups directory
      file:
        state: absent
        path: /tmp/ios_backups/
      become: yes

    - name: Remove Ansible Tower Config Drift template
      tower_job_template:
          name: "iosxe_check_for_configuration_drift"
          job_type: "run"
          project: "Cisco IOS-XE Administration"
          playbook: "ios-drift-detect.yml"
          tower_username: "{{ TOWER_USERNAME }}"
          tower_password: "{{ TOWER_PASSWORD }}"
          tower_host: "{{ TOWER_HOST }}"
          validate_certs: no
          state: absent
      delegate_to: localhost

    - name: Remove Ansible Tower Config Restore template
      tower_job_template:
          name: "iosxe_restore_config_from_backup"
          job_type: "run"
          project: "Cisco IOS-XE Administration"
          playbook: "ios-restore-config.yml"
          tower_username: "{{ TOWER_USERNAME }}"
          tower_password: "{{ TOWER_PASSWORD }}"
          tower_host: "{{ TOWER_HOST }}"
          validate_certs: no
          state: absent
      delegate_to: localhost
