---
- name: Add VRF to ios Routers
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars:
    thestate: merged
    vrf_name: sample_vrf
    vrf_description: added by Ansible

  tasks:

  - name: "Configure the {{ vrf_name }} vrf"
    ios_vrf:
      name: "{{ vrf_name }}"
      description: "{{ vrf_description }}"
      state: present
    when: thestate == "merged"

  - name: "Remove the {{ vrf_name }} vrf"
    ios_vrf:
      name: "{{ vrf_name }}"
      state: absent
    when: thestate == "deleted"
