---
- name: NTP compliance for IOS network elements
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars:
    erase: false

  tasks:

    - name: Get current ntp servers on device
      cisco.ios.ios_command:
        commands: show run | i ntp
      register: output

    - name: Print current ntp servers
      ansible.builtin.debug:
        var: output.stdout_lines

    #adds ntp server entries in the ntp_servers variable if the variable erase is false
    - block:
      - name: Compare ntp servers and remove erroroneous entries
        cisco.ios.ios_config:
          lines: no {{ item }}
        loop: "{{ output.stdout_lines[0] }}"
        when:
          - item not in ntp_servers
          - output.stdout[0].find('ntp') != -1

      - name: Ensure intended ntp servers are present
        cisco.ios.ios_config:
          lines: "{{ item }}"
        loop: "{{ ntp_servers }}"
      when: not erase|bool

    #erases all ntp server entries if the variable erase is true
    - name: Remove all existing ntp server entries
      cisco.ios.ios_config:
        lines: no {{ item }}
      loop: "{{ output.stdout_lines[0] }}"
      when:
        - output.stdout[0].find('ntp') != -1
        - erase|bool
