---
- name: Back up  master config to github
  hosts: cisco
  connection: network_cli
  gather_facts: no
  vars_files:
    - default_vars.yml

  tasks:
    - name: Ensure that running_config directory exists
      file:
        path: "{{ playbook_dir }}/running_config"
        state: directory
        mode: 0777
      run_once: yes
      delegate_to: localhost

    - name: get active configuration from device
      include_role:
        name: ansible-network.config_manager
        tasks_from: get
    - name: copy running config to control node
      copy:
        content: "{{configuration}}"
        dest: "{{ playbook_dir }}/running_config/{{inventory_hostname}}.cfg"

    - name: Remove non-config lines
      lineinfile:
        path: "{{ playbook_dir }}/running_config/{{inventory_hostname}}.cfg"
        line: "Building configuration..."
        state: absent

    - name: Remove non-config lines - Regular Expression
      lineinfile:
        path: "{{ playbook_dir}}/running_config/{{inventory_hostname}}.cfg"
        regexp: 'Current configuration.*'
        state: absent

    - name: clone configuration archives to ansible control
      git:
        repo: "{{ git_repo_path }}"
        dest: "{{ playbook_dir}}/ios-config-archives"
        clone: yes
        force: yes
      run_once: yes
      delegate_to: localhost

    - name: copy running configs to ios-config-archives
      command: "cp -f {{ playbook_dir}}/running_config/{{inventory_hostname}}.cfg {{ playbook_dir}}/ios-config-archives/{{inventory_hostname}}_master.cfg"
      delegate_to: localhost

    #TODO: replace with an API call to do a git push
    - name: Instruct Operator to back up to github
      debug:
        msg: "Operator: Manually push ios-config-archives to Github"
      delegate_to: localhost
      run_once: yes

    # - name: Push ios-config-archives to github
    #   uri:
    #     url: https://api.github.com/graphql
