- hosts: ios
  connection: network_cli
  vars_files:
    - ./vars/interfaces.yml

  tasks:
  # - name: Generate IOS-XR Config
  #   template:
  #     src: "{{ item.src }}"
  #     dest: "{{ item.dest }}"
  #   with_items:
  #     - {src: 'interface.j2',dest: 'interfaces.config'}


  - name: Generate IOS-XR Config
    cli_config:
      config: "{{ lookup('template', './templates/interfaces.j2') }}"
