- hosts: ios
  connection: local
  vars_files:
    - vars.yml

  tasks:
  - name: Generate IOS-XR Config
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - {src: 'interface.j2',dest: 'interfaces.config'}
